### ISSUE TITLE
Turbolink issue control-button

### ISSUE THREAD

**Issue by ghost** [benschwarz/gallery-css#34]
Thanks for this awesome library @benschwarz!

As I was testing this awesome piece of craftsmanship, I stumbled upon a problem where the control-buttons don't seem to work when using gallery-css together with turbolinks. This can easily be fixed of course by disabling turbolinks entirely, or disabling it for the links that don't work. Still I thought it should be nice to let you know that currently this problem is present.

**Comment by benschwarz** [comment]
Hey @git-jls, thank you! 🐳

Seeing as turbolinks decides to take-over links entirely, there isn't a lot that can be done here (because gallery-css uses hash-links via `:target`). However, you can [disable turbolinks on single links](http://stackoverflow.com/questions/14227363/using-turbolinks-in-a-rails-link-to), so that might be worth adding to your codebase.
